// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvSubscription.Data;

#nullable disable

namespace Tv.Migrations
{
    [DbContext(typeof(TvContext))]
    [Migration("20220615145807_first5")]
    partial class first5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TvSubscription.Model.Channel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Subscribers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fun kids",
                            Name = "Nickelodeon",
                            OwnerId = 1,
                            Subscribers = "Spitzila 10.03.2014"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Benga benga",
                            Name = "Weceu",
                            OwnerId = 2,
                            Subscribers = "Zaris 15.06.2022; Spitzila 15.06.2022; Olex 12.02.2001"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nazi",
                            Name = "Mein Fuhrer",
                            OwnerId = 3,
                            Subscribers = "Spitzila 15.06.2022; Olex 12.02.2001"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Naruto",
                            Name = "Minimax",
                            OwnerId = 1,
                            Subscribers = "Olex 12.02.2001"
                        });
                });

            modelBuilder.Entity("TvSubscription.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Gender = "male",
                            Name = "Zaris"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Gender = "male",
                            Name = "Olex"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Gender = "female",
                            Name = "Spitzila"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
